version: '3.1'
services:

  db:
    ports:
      - 5432:5432
    networks:
      - default

  api:
    container_name: mobydq-api
    #restart: always
    image: mobydq-api
    build:
      context: ./api
    volumes:
      - ./api/init:/srv/api/
    environment:
      FLASK_APP: api.py
      FLASK_RUN_PORT: 5434
      OAUTHLIB_INSECURE_TRANSPORT: 1
      TOKEN_ISSUER: ${HOST_NAME}
      AFTER_LOGIN_REDIRECT: ${HOST_NAME}
    ports:
      - 5434:5434
    depends_on:
      - graphql
    networks:
      - default
    command: ["flask", "run", "--host=0.0.0.0"]
    secrets:
      - public_key
      - private_key

  scripts:
    container_name: mobydq-scripts
    #restart: always
    image: mobydq-scripts
    build:
      context: ./scripts
      args:
        - MAIL_HOST=${MAIL_HOST}
        - MAIL_PORT=${MAIL_PORT}
        - MAIL_SENDER=${MAIL_SENDER}
        - MAIL_PASSWORD=${MAIL_PASSWORD}
    env_file:
      - ./.env
    depends_on:
      - graphql
    networks:
      - default

  app:
    container_name: mobydq-app
    #restart: always
    image: mobydq-app
    build:
      context: ./app
    volumes:
      - ./app/src:/usr/src/app/src:ro
      - ./app/public:/usr/src/app/public:ro
    ports:
      - 80:3000
    depends_on:
      - api
      - graphql
    networks:
      - default

networks:
  default:
    external:
      name: mobydq-network

volumes:
  mobydq-db-volume:
    external: true

secrets:
  public_key:
    file: public.pem
  private_key:
    file: private.pem
